#!/bin/bash
#-----------------------------------------------------------
# Program   : tprune
# Location  : ~/lib/bfw/sh
# Author    : Scott Smith <scott@bashify.com>
# Purpose   : Read info from a bfw source module
# Copyright (c) 2013 Scott Smith <scott@bashify.com>
#-----------------------------------------------------------

if [ "bfw_bash_framework" ]
then
  [ "${bfw[debug]}" = "ON" ] && debug_on
  bfw_script_version "2013-05-28"
else
  echo "error: bfw scripts cannot be run directly"
  exit 99
fi

#-----------------------------------------------------------

USAGE="usage:	${bfw[script]} tree_file branch_name"

HELP="\
where:	branch_name is the fully qualified path of the branch
	to prune out of the tree file, and if it does not begin
	with a / it is assumed to be a subdirectory immediately
	off the base path used to create the tree_file

	If tree_file is '-' then read from stdin.
"

#-----------------------------------------------------------

cleanup()
{
  rm -f /tmp/tprune.$$.* &>/dev/null
}

#-----------------------------------------------------------

case "$1" in
--help) help ;;
-*|"") usage ;;
esac

[ $# -eq 2 ] || die 1 "$USAGE"

SOURCE="$1"
BRANCH="${2%/}"

if [ "$SOURCE" = "-" ]
then
  SOURCE=/dev/stdin
elif [ ! -f "$SOURCE" ]
then
  die 2 "\nerror:\tfile not found '$SOURCE'\n"
fi

# remove trailing / and . characters from BRANCH
# and replace any repeating strings of / and . with a /

BRANCH="$(sed 's#[./]*$##; s#/[./]*/#/#g' <<<"$BRANCH")"

# error check to make sure we're doing something useful

TOP="$(head -1 "$SOURCE")"
[ "${BRANCH:0:1}" = "/" ] || BRANCH="$TOP/$BRANCH"

[ "$TOP" = "$BRANCH" ] && die 3 "\nerror:\tbranch_name == tree_file base path\n\n\tthe branch name cannot be the same as the top level path\n\tused to create the tree file, which is:\n\n\t$TOP\n"

CUT="${BRANCH#$TOP/}"
[ "$CUT" = "$BRANCH" ] && die 4 "\nerror:\tbranch_name !~ tree file base path\n\n\tthe branch name does not contain the top level path used\n\tto create the tree file, which is:\n\n\t$TOP\n"

#-----------------------------------------------------------

# setup to allow pruning into about 20 levels deep
# DASHES is used to create the leader strings
# LEVELS is a count of the '/' chars in the path to CUT
# MAXDASH is the length of the leader for the CUT path

DASHES="----------------------------------------"

LEVELS=$(( $(tr -c -d / <<<"$CUT" | wc -c) + 1 ))

MAXDASH=$(( LEVELS * 2 - 1 ))

# split the CUT path into an array, used in the 'for' loop

oIFS="$IFS" IFS=/ SEG=(root $CUT) IFS="$oIFS"

# start reading the input and cycle through each path level in CUT

F1="$SOURCE"

for ((n=1; n<=$LEVELS; n++))
do
  F2="/tmp/tprune.$$.$n"
  PREFIX="${DASHES:0:$((n*2-1))}"
  sed "0,/^|$PREFIX${SEG[$n]}$/ d" <"$F1" >"$F2"
  F1="$F2"
done

# F1 now contains the lines starting with the line AFTER the CUT
# so the starting point is SOURCE - F1 lines in, and the stopping
# point will be the first line with the same level leader (or if
# no leader found, then the end of the file)

START=$(( $(wc -l <"$SOURCE") - $(wc -l <"$F1") ))

STOP="$(egrep -nm 1 "^\|-{1,$MAXDASH}[^-]" <"$F1" | cut -d: -f1)"

[ -z "$STOP" ] && STOP='$' || STOP=$(( START+STOP-1 ))

sed "$START,$STOP d" <"$SOURCE"

die 0 -

#EOF(tprune)
